"""Compile locales/<language>.json into Msg.java (key constants) and I18nCatalog.java (texts).

Each locale file is a flat JSON object: message key -> text. Keys are dotted lowercase names
(`settings.led.port`); texts use positional placeholders {0}, {1}. English is the reference
language: every key must exist in every file. The game's Resources are intentionally untouched.
"""
import argparse,json,re
from pathlib import Path

LANGUAGES=['en','ko','zh-Hans']
KEY=re.compile(r'[a-z][a-z0-9_]*(\.[a-z0-9_]+)+')
PLACEHOLDER=re.compile(r'\{(\d+)\}')
HANGUL=re.compile('[가-힣ᄀ-ᇿ㄰-㆏]')
HAN=re.compile('[㐀-鿿]')
root=Path(__file__).resolve().parents[1]
src=root/'app/src/main/java/io/oniimai/kanade'

def unique(pairs):
    out={}
    for key,value in pairs:
        if key in out:raise ValueError('Duplicate locale key: '+key)
        out[key]=value
    return out

def load():
    catalogues={lang:json.loads((root/'locales'/(lang+'.json')).read_text(encoding='utf-8'),object_pairs_hook=unique) for lang in LANGUAGES}
    keys=list(catalogues['en'])
    assert keys==sorted(keys),'Keep locales/en.json sorted by key'
    for lang,messages in catalogues.items():
        assert set(messages)==set(keys),(lang,'keys differ from en.json',sorted(set(messages)^set(keys)))
        for key,text in messages.items():
            assert KEY.fullmatch(key),('Invalid key',key)
            assert isinstance(text,str) and text.strip(),(lang,key,'empty text')
            assert sorted(set(PLACEHOLDER.findall(text)))==sorted(set(PLACEHOLDER.findall(catalogues['en'][key]))),(lang,key,'placeholders differ from English')
            assert text.count('\n')==catalogues['en'][key].count('\n'),(lang,key,'line count differs from English')
            if lang=='en':assert not HANGUL.search(text) and not HAN.search(text),(key,'English text contains Korean/Chinese')
            if lang=='zh-Hans':assert not HANGUL.search(text),(key,'Chinese text contains Korean')
    return keys,catalogues

def constant(key):return key.upper().replace('.','_')
def literal(text):return json.dumps(text,ensure_ascii=False)

def render(keys,catalogues):
    msg=['// Generated by scripts/generate_locales.py from locales/*.json. Do not edit.','package io.oniimai.kanade;','',
         '/** Message ids: each constant is its locale key in upper case. Look texts up with I18n.t(Msg.KEY, args...). */',
         'final class Msg {','    private Msg(){}']
    for i,key in enumerate(keys):msg.append(f'    static final int {constant(key)}={i};')
    msg+=['}','']
    cat=['// Generated by scripts/generate_locales.py from locales/*.json. Do not edit.','package io.oniimai.kanade;','',
         'final class I18nCatalog {','    private I18nCatalog(){}',
         '    static final String[] LANGUAGES={'+','.join(literal(l) for l in LANGUAGES)+'};',
         '    static final String[] KEYS={']
    cat+=[f'        {literal(k)},' for k in keys]
    cat+=['    };','    static final String[][] TEXT={']
    for lang in LANGUAGES:
        cat.append(f'        {{ // {lang}')
        cat+=[f'            {literal(catalogues[lang][k])},' for k in keys]
        cat.append('        },')
    cat+=['    };','}','']
    return '\n'.join(msg),'\n'.join(cat)

def main():
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    keys,catalogues=load()
    outputs=dict(zip(['Msg.java','I18nCatalog.java'],render(keys,catalogues)))
    for name,text in outputs.items():
        dest=src/name
        if a.check:assert dest.read_bytes().decode('utf-8')==text,name+' is stale: run scripts/generate_locales.py'
        else:dest.write_bytes(text.encode('utf-8'))
    print(f'Locale catalogues verified: {len(keys)} messages in {", ".join(LANGUAGES)}')

if __name__=='__main__':main()
