"""Generate the in-module catalogue; target-app Resources are intentionally untouched."""
import argparse,json,re
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
root=Path(__file__).resolve().parents[1]
def unique(pairs):
    out={}
    for key,value in pairs:
        if key in out:raise ValueError('Duplicate locale key: '+key)
        out[key]=value
    return out
entries=json.loads((root/'locales/ko-zh-Hans.json').read_text(encoding='utf-8'),object_pairs_hook=unique)
lines=['package io.oniimai.kanade;','','// Generated by scripts/generate_locales.py from locales/ko-zh-Hans.json.',
       'final class UiTextCatalog {','    static final java.util.Map<String,String> CHINESE;','    static {',
       '        java.util.Map<String,String> text=new java.util.LinkedHashMap<>();']
for ko,zh in entries.items():
    assert isinstance(ko,str) and isinstance(zh,str) and ko and zh.strip(),ko
    assert not re.search('[가-힣]',zh),ko
    assert ko.count('\n')==zh.count('\n'),ko
    lines.append('        text.put('+json.dumps(ko,ensure_ascii=False)+','+json.dumps(zh,ensure_ascii=False)+');')
lines+=['        CHINESE=java.util.Collections.unmodifiableMap(text);','    }','}','']
result='\n'.join(lines);dest=root/'app/src/main/java/io/oniimai/kanade/UiTextCatalog.java'
if a.check:assert dest.read_text(encoding='utf-8')==result,'Generated catalogue is stale'
else:dest.write_text(result,encoding='utf-8')
print('Locale catalogue verified:',len(entries),'Korean / Simplified Chinese entries')
