#pragma once
#include <stdint.h>
#include <stddef.h>
#include "target_fingerprint.h"
// Select one complete profile by ELF build ID before any game address is used.
// Never mix addresses/signatures between builds or fall back to a nearby version.
struct TargetBuild {
    const unsigned char* buildId;
    size_t buildIdSize;
    const char* name;
    uintptr_t RVA_TOUCH;
    uint64_t SIG_TOUCH;
    uintptr_t RVA_FRAME;
    uint64_t SIG_FRAME;
    uintptr_t RVA_RAW;
    uint64_t SIG_RAW;
    uintptr_t RVA_DOWN;
    uint64_t SIG_DOWN;
    uintptr_t RVA_LED_COLOR;
    uint64_t SIG_LED_COLOR;
    uintptr_t RVA_LED_PRESS;
    uint64_t SIG_LED_PRESS;
    uintptr_t RVA_LED_ALL;
    uint64_t SIG_LED_ALL;
    uintptr_t RVA_LED_OFF;
    uint64_t SIG_LED_OFF;
    uintptr_t RVA_LED_FADE;
    uint64_t SIG_LED_FADE;
    uintptr_t RVA_LED_RING;
    uint64_t SIG_LED_RING;
    uintptr_t RVA_LED_FET;
    uint64_t SIG_LED_FET;
    uintptr_t RVA_LED_RING_FADE;
    uint64_t SIG_LED_RING_FADE;
    uintptr_t RVA_GAME_START;
    uint64_t SIG_GAME_START;
    uintptr_t RVA_GAME_RELEASE;
    uint64_t SIG_GAME_RELEASE;
    uintptr_t RVA_RESULT_START;
    uint64_t SIG_RESULT_START;
    uintptr_t RVA_RESULT_RELEASE;
    uint64_t SIG_RESULT_RELEASE;
    uintptr_t RVA_SCORE_UPDATE;
    uint64_t SIG_SCORE_UPDATE;
    uintptr_t RVA_SCORE_UTAGE;
    uint64_t SIG_SCORE_UTAGE;
    uintptr_t RVA_SCORE_FINISH;
    uint64_t SIG_SCORE_FINISH;
    uintptr_t RVA_MUSIC_GET;
    uint64_t SIG_MUSIC_GET;
    uintptr_t RVA_NOTES_UPDATE;
    uint64_t SIG_NOTES_UPDATE;
    uintptr_t RVA_CURRENT_MSEC;
    uint64_t SIG_CURRENT_MSEC;
    uintptr_t RVA_UI_SETTINGS_CCTOR;
    uint64_t SIG_UI_SETTINGS_CCTOR;
    uintptr_t RVA_UI_SETTINGS_LOAD;
    uint64_t SIG_UI_SETTINGS_LOAD;
    uintptr_t RVA_UI_CONTROL_UPDATE;
    uint64_t SIG_UI_CONTROL_UPDATE;
    uintptr_t RVA_UI_PREFS_GETINT;
    uint64_t SIG_UI_PREFS_GETINT;
    uintptr_t RVA_UI_PREFS_SETINT;
    uint64_t SIG_UI_PREFS_SETINT;
    uintptr_t RVA_UI_PREFS_SAVE;
    uint64_t SIG_UI_PREFS_SAVE;
    uintptr_t RVA_UI_GROUP_ALPHA_GET;
    uint64_t SIG_UI_GROUP_ALPHA_GET;
    uintptr_t RVA_UI_GROUP_ALPHA_SET;
    uint64_t SIG_UI_GROUP_ALPHA_SET;
    uintptr_t RVA_UI_GROUP_INTERACTABLE_GET;
    uint64_t SIG_UI_GROUP_INTERACTABLE_GET;
    uintptr_t RVA_UI_GROUP_RAYCAST_GET;
    uint64_t SIG_UI_GROUP_RAYCAST_GET;
    uintptr_t RVA_UI_GROUP_RAYCAST_SET;
    uint64_t SIG_UI_GROUP_RAYCAST_SET;
    uintptr_t RVA_UI_OBJECT_ALIVE;
    uint64_t SIG_UI_OBJECT_ALIVE;
    uintptr_t DATA_UI_SETTINGS_TYPEINFO;
    uintptr_t FIELD_UI_MAIN_GROUP;
    uintptr_t RVA_BOOT_UPDATE;
    uint64_t SIG_BOOT_UPDATE;
    uintptr_t RVA_BOOT_STARTED;
    uint64_t SIG_BOOT_STARTED;
    uintptr_t RVA_BOOT_CANVAS;
    uint64_t SIG_BOOT_CANVAS;
    uintptr_t RVA_BOOT_BUTTON_PRESS;
    uint64_t SIG_BOOT_BUTTON_PRESS;
    uintptr_t RVA_BOOT_ACTIVE;
    uint64_t SIG_BOOT_ACTIVE;
    uintptr_t RVA_BOOT_INTERACTABLE;
    uint64_t SIG_BOOT_INTERACTABLE;
    uintptr_t FIELD_BOOT_START_BUTTON;
    uintptr_t FIELD_BOOT_START_CALLBACK;
    uintptr_t RVA_ALBUM_INSTANCE;
    uint64_t SIG_ALBUM_INSTANCE;
    uintptr_t RVA_ALBUM_JACKET;
    uint64_t SIG_ALBUM_JACKET;
    uintptr_t RVA_ALBUM_SELECTED;
    uint64_t SIG_ALBUM_SELECTED;
    uintptr_t RVA_AIME_UPDATE;
    uint64_t SIG_AIME_UPDATE;
    uintptr_t RVA_AIME_START;
    uint64_t SIG_AIME_START;
    uintptr_t RVA_AIME_USE;
    uint64_t SIG_AIME_USE;
    uintptr_t RVA_AIME_MANAGER_EXECUTE;
    uint64_t SIG_AIME_MANAGER_EXECUTE;
    uintptr_t RVA_AIME_ERROR_POLL;
    uint64_t SIG_AIME_ERROR_POLL;
    uintptr_t RVA_AIME_ERROR_RESULT;
    uint64_t SIG_AIME_ERROR_RESULT;
    uintptr_t RVA_AIME_ERROR_WINDOW;
    uint64_t SIG_AIME_ERROR_WINDOW;
    uintptr_t RVA_AIME_UNIT_START;
    uint64_t SIG_AIME_UNIT_START;
    uintptr_t RVA_LED_PWM;
    uint64_t SIG_LED_PWM;
    uintptr_t RVA_LED_BLOCK_COLOR;
    uint64_t SIG_LED_BLOCK_COLOR;
    uintptr_t RVA_AIME_ADVCHECK;
    uint64_t SIG_AIME_ADVCHECK;
    uintptr_t RVA_AIME_ANYREAD;
    uint64_t SIG_AIME_ANYREAD;
};
#include "target_160.h"
#include "target_165.h"
static inline const TargetBuild* targetByBuildId(const unsigned char* id,size_t size) {
    if(!id)return nullptr;
    const TargetBuild* profiles[]={&Target160::PROFILE,&Target165::PROFILE};
    for(const auto* profile:profiles){
        if(size!=profile->buildIdSize)continue;
        size_t i=0;for(;i<size&&id[i]==profile->buildId[i];++i){}
        if(i==size)return profile;
    }
    return nullptr;
}
